class IntelligenceReport:
    """
    Displays intelligence generated by the system.
    """

    def display(
        self,
        signal,
    ):

        print("\n========== Intelligence ==========\n")

        print(f"Project      : {signal.project}")
        print(f"Category     : {signal.category}")
        print(f"Signal       : {signal.signal_type}")
        print(f"Source       : {signal.source}")
        print(f"Score        : {signal.score}")
        print(f"Confidence   : {signal.confidence}%")
        print(f"Severity     : {signal.severity}")
        print(f"Title        : {signal.title}")
        print(f"Summary      : {signal.summary}")

        print()


intelligence_report = IntelligenceReport()