"""Protocol for future resolution strategy and policy registries."""
from typing import Protocol
from .resolution_policy import ResolutionPolicy
from .resolution_strategy import ResolutionStrategy

class ResolutionRegistry(Protocol):
    def register_policy(self, policy: ResolutionPolicy) -> None: ...
    def register_strategy(self, strategy: ResolutionStrategy) -> None: ...
    def get_policy(self, name: str) -> ResolutionPolicy | None: ...
    def get_strategy(self, name: str) -> ResolutionStrategy | None: ...
