from typing import Protocol
from .pipeline_stage import PipelineStage
class RuntimeComponent(Protocol):
    def execute(self, context: object) -> object: ...
class ExecutionRegistry(Protocol):
    def register(self, stage: PipelineStage, component: RuntimeComponent) -> None: ...
    def get(self, stage: PipelineStage) -> RuntimeComponent | None: ...
