from typing import Protocol
from .graph_adapter import GraphAdapter
class GraphRegistry(Protocol):
    def register(self, name: str, adapter: GraphAdapter) -> None: ...
    def get(self, name: str) -> GraphAdapter | None: ...
