from typing import Protocol, Any
from src.runtime.durable import ExecutionJob, ExecutionSnapshot, ExecutionCheckpoint
class ExecutionStore(Protocol):
    def save(self, job: ExecutionJob) -> None: ...
    def get(self, execution_id: str) -> ExecutionJob | None: ...
    def update(self, snapshot: ExecutionSnapshot) -> None: ...
class CheckpointStore(Protocol):
    def save(self, checkpoint: ExecutionCheckpoint) -> None: ...
    def latest(self, execution_id: str) -> ExecutionCheckpoint | None: ...
class EventStore(Protocol):
    def append(self, event: Any) -> None: ...
class GraphStore(Protocol):
    def upsert(self, value: Any) -> None: ...
class EvidenceStore(Protocol):
    def save(self, value: Any) -> None: ...
class FindingStore(Protocol):
    def save(self, value: Any) -> None: ...
class AssessmentStore(Protocol):
    def save(self, value: Any) -> None: ...
class SignalStore(Protocol):
    def save(self, value: Any) -> None: ...
class ProfileStore(Protocol):
    def save(self, value: Any) -> None: ...
