from typing import Protocol
from .compiler import Compiler
class CompilerRegistry(Protocol):
    def register(self, name: str, compiler: Compiler) -> None: ...
    def get(self, name: str) -> Compiler | None: ...
