from typing import Protocol, TypeVar

from src.core_intelligence.models import Assessment, Evidence, Finding, Observation, Signal

Model = TypeVar("Model", Observation, Evidence, Finding, Assessment, Signal)


class ValidationResult(Protocol):
    @property
    def valid(self) -> bool: ...

    @property
    def errors(self) -> tuple[str, ...]: ...


class ModelValidator(Protocol[Model]):
    def validate(self, value: Model) -> ValidationResult: ...


class ObservationValidator(ModelValidator[Observation], Protocol): ...
class EvidenceValidator(ModelValidator[Evidence], Protocol): ...
class FindingValidator(ModelValidator[Finding], Protocol): ...
class AssessmentValidator(ModelValidator[Assessment], Protocol): ...
class SignalValidator(ModelValidator[Signal], Protocol): ...
