from typing import Protocol
from .reasoning_provider import ReasoningProvider
from .reasoning_strategy import ReasoningStrategy
class ReasoningRegistry(Protocol):
    def register_provider(self, name: str, provider: ReasoningProvider) -> None: ...
    def register_strategy(self, name: str, strategy: ReasoningStrategy) -> None: ...
    def get_provider(self, name: str) -> ReasoningProvider | None: ...
    def get_strategy(self, name: str) -> ReasoningStrategy | None: ...
