AI_QUERY_PACK = {

    "hashtags": [

        "#AI",
        "#ArtificialIntelligence",
        "#MachineLearning",
        "#DeepLearning",
        "#GenerativeAI",
        "#GenAI",
        "#LLM",
        "#FoundationModels",
        "#AIAgents",
        "#AgenticAI",
        "#MultiAgentSystems",
        "#RAG",
        "#PromptEngineering",
        "#ContextEngineering",
        "#MLOps",
        "#AIInfrastructure",
        "#GPU",
        "#Robotics",
        "#AISafety",
        "#AIAlignment",
        "#AISecurity",
        "#OpenSourceAI",
        "#DecentralizedAI",
        "#Web3AI",
        "#DeAI",
        "#AIResearch",
        "#AIStartups",
        "#AIProducts"

    ],

    "keywords": [

        "Artificial Intelligence",
        "Machine Learning",
        "Deep Learning",
        "Neural Network",
        "Neural Architecture",
        "Representation Learning",
        "Supervised Learning",
        "Unsupervised Learning",
        "Self-Supervised Learning",
        "Reinforcement Learning",
        "Reinforcement Learning from Human Feedback",
        "RLHF",
        "Direct Preference Optimization",
        "DPO",
        "Constitutional AI",
        "Large Language Model",
        "LLM",
        "Small Language Model",
        "SLM",
        "Foundation Model",
        "Multimodal Model",
        "World Model",
        "Reasoning Model",
        "Language Model",
        "Transformer",
        "Mixture of Experts",
        "MoE",
        "Diffusion Model",
        "Generative AI",
        "Generative Model",
        "Text to Image",
        "Text to Video",
        "Text to Speech",
        "Speech to Text",
        "Computer Vision",
        "Natural Language Processing",
        "NLP",
        "Multimodal AI",
        "AI Agent",
        "Agentic AI",
        "Autonomous Agent",
        "Multi-Agent System",
        "Agent Framework",
        "Agent Orchestration",
        "Agentic Workflow",
        "AI Copilot",
        "AI Assistant",
        "Tool Calling",
        "Function Calling",
        "Model Context Protocol",
        "MCP",
        "Retrieval Augmented Generation",
        "RAG",
        "GraphRAG",
        "Agentic RAG",
        "Vector Database",
        "Vector Search",
        "Embedding",
        "Embedding Model",
        "Semantic Search",
        "Knowledge Graph",
        "Knowledge Base",
        "Document Intelligence",
        "Prompt Engineering",
        "Prompt Optimization",
        "Prompt Injection",
        "Context Engineering",
        "Context Window",
        "Long Context",
        "In-Context Learning",
        "System Prompt",
        "Fine-Tuning",
        "Instruction Tuning",
        "Parameter-Efficient Fine-Tuning",
        "LoRA",
        "QLoRA",
        "Model Training",
        "Pretraining",
        "Post-Training",
        "Distillation",
        "Quantization",
        "Pruning",
        "Model Compression",
        "Synthetic Data",
        "Training Data",
        "Data Curation",
        "Data Labeling",
        "Evaluation Benchmark",
        "Model Evaluation",
        "LLM Evaluation",
        "Inference",
        "Inference Engine",
        "Inference Optimization",
        "Model Serving",
        "Batch Inference",
        "Real-Time Inference",
        "Edge AI",
        "On-Device AI",
        "GPU Computing",
        "GPU Cluster",
        "GPU Cloud",
        "AI Accelerator",
        "Tensor Processing Unit",
        "TPU",
        "Neural Processing Unit",
        "NPU",
        "High Performance Computing",
        "HPC",
        "Distributed Training",
        "Distributed Inference",
        "AI Infrastructure",
        "AI Compute",
        "Compute Network",
        "MLOps",
        "LLMOps",
        "Model Registry",
        "Feature Store",
        "Data Pipeline",
        "AI Observability",
        "Model Monitoring",
        "Model Routing",
        "AI Gateway",
        "AI Security",
        "AI Safety",
        "AI Alignment",
        "AI Governance",
        "Responsible AI",
        "Model Risk Management",
        "Red Teaming",
        "Jailbreak",
        "Adversarial Machine Learning",
        "Data Poisoning",
        "Model Privacy",
        "Open Source AI",
        "Open Weight Model",
        "Open Model",
        "Decentralized AI",
        "Decentralized Compute",
        "Decentralized Inference",
        "Decentralized Training",
        "Web3 AI",
        "Crypto AI",
        "On-Chain AI",
        "AI x Crypto",
        "AI Protocol",
        "AI Network",
        "AI Marketplace",
        "AI Token",
        "Proof of Intelligence",
        "Bittensor",
        "TAO",
        "Bittensor Subnet",
        "Virtuals Protocol",
        "G.A.M.E",
        "Fetch.ai",
        "ASI Alliance",
        "SingularityNET",
        "Ocean Protocol",
        "Render Network",
        "Akash Network",
        "io.net",
        "Aethir",
        "Gensyn",
        "Ritual",
        "Nous Research",
        "Sahara AI",
        "Sentient",
        "Morpheus",
        "Kaito AI",
        "ElizaOS",
        "ai16z",
        "Autonolas",
        "Olas",
        "Ora Protocol",
        "Allora Network",
        "Nillion",
        "Grass",
        "Vana",
        "Prime Intellect",
        "OpenAI",
        "Anthropic",
        "Google DeepMind",
        "Meta AI",
        "Mistral AI",
        "xAI",
        "Cohere",
        "Hugging Face",
        "NVIDIA",
        "AMD",
        "Cerebras",
        "Groq",
        "Together AI",
        "Fireworks AI",
        "Perplexity",
        "LangChain",
        "LangGraph",
        "LlamaIndex",
        "Haystack",
        "AutoGen",
        "CrewAI",
        "Semantic Kernel",
        "PyTorch",
        "TensorFlow",
        "JAX",
        "vLLM",
        "TensorRT-LLM",
        "Ollama",
        "MLflow",
        "Weights and Biases",
        "Pinecone",
        "Weaviate",
        "Milvus",
        "Qdrant",
        "Chroma",
        "FAISS",
        "Robotics",
        "Humanoid Robot",
        "Physical AI",
        "Autonomous Vehicle",
        "AI Research",
        "AI Startup",
        "AI Developer Tool",
        "AI API",
        "AI SDK"

    ],

    "boolean_queries": [

        "AI AND partnership",
        "AI AND collaboration",
        "AI AND strategic partnership",
        "AI AND funding",
        "AI AND investment round",
        "AI AND seed round",
        "AI AND Series A",
        "AI AND grant",
        "AI AND acquisition",
        "AI AND valuation",
        "AI AND launch",
        "AI AND mainnet",
        "AI AND testnet",
        "AI AND beta release",
        "AI AND product release",
        "AI AND roadmap",
        "AI AND upgrade",
        "AI AND protocol upgrade",
        "AI AND integration",
        "AI AND API integration",
        "AI AND developer SDK",
        "AI AND developer tools",
        "AI AND GitHub release",
        "AI AND open source",
        "AI AND hackathon",
        "AI AND grant program",
        "AI AND ecosystem growth",
        "AI AND adoption",
        "AI AND enterprise adoption",
        "AI AND user growth",
        "AI AND governance",
        "AI AND proposal",
        "AI AND DAO vote",
        "AI AND token launch",
        "AI AND tokenomics",
        "AI AND airdrop",
        "AI AND exploit",
        "AI AND vulnerability",
        "AI AND security incident",
        "AI AND data breach",
        "AI AND audit",
        "AI AND research",
        "AI AND research paper",
        "AI AND benchmark",
        "AI AND model release",
        "AI AND foundation model",
        "AI AND LLM",
        "AI agent AND launch",
        "AI agent AND partnership",
        "AI agent AND funding",
        "AI agent AND integration",
        "AI agent AND adoption",
        "multi-agent AND protocol",
        "RAG AND launch",
        "RAG AND integration",
        "vector database AND funding",
        "vector database AND partnership",
        "inference AND infrastructure",
        "inference AND GPU",
        "AI compute AND capacity",
        "GPU cloud AND expansion",
        "GPU cluster AND deployment",
        "decentralized AI AND partnership",
        "decentralized AI AND funding",
        "decentralized AI AND launch",
        "decentralized AI AND governance",
        "Web3 AI AND integration",
        "Web3 AI AND ecosystem",
        "Bittensor AND subnet",
        "Bittensor AND governance",
        "Bittensor AND partnership",
        "Virtuals Protocol AND launch",
        "Virtuals Protocol AND partnership",
        "Fetch.ai AND integration",
        "ASI Alliance AND update",
        "SingularityNET AND roadmap",
        "Ocean Protocol AND data",
        "Render Network AND GPU",
        "Akash Network AND AI",
        "io.net AND GPU",
        "Aethir AND infrastructure",
        "Gensyn AND training",
        "Ritual AND protocol",
        "Sahara AI AND data",
        "OpenAI AND launch",
        "Anthropic AND model",
        "Google DeepMind AND research",
        "NVIDIA AND AI infrastructure",
        "Hugging Face AND open source",
        "LangChain AND integration",
        "MCP AND adoption"

    ]

}
