DEFI_QUERY_PACK = {

    "hashtags": [

        "#DeFi",
        "#DecentralizedFinance",
        "#DeFiLlama",
        "#DEX",
        "#AMM",
        "#DeFiYield",
        "#YieldFarming",
        "#Liquidity",
        "#LiquidityMining",
        "#Lending",
        "#Stablecoins",
        "#Staking",
        "#LiquidStaking",
        "#Restaking",
        "#LiquidRestaking",
        "#DeFiSafety",
        "#DeFiSecurity",
        "#DeFiGovernance",
        "#DeFiTVL",
        "#RealWorldAssets",
        "#RWA",
        "#Perpetuals",
        "#OnchainFinance",
        "#CrossChain",
        "#MEV",
        "#DeFiInfrastructure",
        "#DeFiInnovation"

    ],

    "keywords": [

        "Decentralized Finance",
        "DeFi",
        "On-Chain Finance",
        "Composable Finance",
        "Permissionless Finance",
        "Automated Market Maker",
        "AMM",
        "Decentralized Exchange",
        "DEX",
        "Order Book DEX",
        "Intent-Based Trading",
        "Intent Solver",
        "Liquidity Pool",
        "Liquidity Provider",
        "LP Token",
        "Concentrated Liquidity",
        "Liquidity Mining",
        "Liquidity Incentive",
        "Liquidity Bootstrapping Pool",
        "Cross-Chain Liquidity",
        "Liquidity Fragmentation",
        "Lending",
        "Borrowing",
        "Money Market",
        "Lending Pool",
        "Overcollateralized Loan",
        "Undercollateralized Loan",
        "Collateral",
        "Collateral Factor",
        "Loan-to-Value",
        "Liquidation",
        "Liquidation Threshold",
        "Liquidation Penalty",
        "Interest Rate Model",
        "Borrow Rate",
        "Supply Rate",
        "Utilization Rate",
        "Credit Delegation",
        "Flash Loan",
        "Flash Mint",
        "Yield Farming",
        "Yield Aggregator",
        "Yield Strategy",
        "Yield Tokenization",
        "Yield Bearing Asset",
        "Yield Curve",
        "Vault",
        "Automated Vault",
        "Strategy Vault",
        "Delta-Neutral Strategy",
        "Structured Product",
        "Principal Protected Product",
        "Fixed Yield",
        "Fixed Income DeFi",
        "Staking",
        "Liquid Staking",
        "Liquid Staking Token",
        "LST",
        "Restaking",
        "Liquid Restaking",
        "Liquid Restaking Token",
        "LRT",
        "Shared Security",
        "Actively Validated Service",
        "AVS",
        "Stablecoin",
        "Decentralized Stablecoin",
        "Collateralized Debt Position",
        "CDP",
        "Synthetic Dollar",
        "Algorithmic Stablecoin",
        "Yield-Bearing Stablecoin",
        "Stablecoin Liquidity",
        "Stablecoin Reserve",
        "Real World Asset",
        "RWA",
        "Tokenized Treasury",
        "Tokenized Credit",
        "Tokenized Money Market Fund",
        "Private Credit",
        "DeFi Derivatives",
        "Perpetual Futures",
        "Perpetual Swap",
        "Perpetual DEX",
        "Options Protocol",
        "On-Chain Options",
        "Futures Protocol",
        "Prediction Market",
        "Interest Rate Swap",
        "Basis Trade",
        "Funding Rate",
        "Open Interest",
        "Oracle Network",
        "Price Oracle",
        "Oracle Update",
        "Oracle Manipulation",
        "Chainlink",
        "Chainlink CCIP",
        "Pyth Network",
        "RedStone",
        "API3",
        "UMA Optimistic Oracle",
        "MEV",
        "Maximal Extractable Value",
        "MEV Boost",
        "MEV Relay",
        "MEV Protection",
        "Sandwich Attack",
        "Front Running",
        "Back Running",
        "Transaction Order Flow",
        "Bridge",
        "Cross-Chain Bridge",
        "Bridge Security",
        "Cross-Chain Messaging",
        "LayerZero",
        "Wormhole",
        "Axelar",
        "Across Protocol",
        "Hyperlane",
        "Stargate",
        "Aave",
        "Aave V3",
        "Aave DAO",
        "Aave GHO",
        "Compound",
        "Compound III",
        "Compound DAO",
        "MakerDAO",
        "Sky",
        "Sky Dollar",
        "Spark",
        "SparkLend",
        "Uniswap",
        "Uniswap V4",
        "Uniswap Hooks",
        "Uniswap DAO",
        "Curve Finance",
        "Curve Pool",
        "crvUSD",
        "Balancer",
        "Balancer V3",
        "Pendle",
        "Pendle PT",
        "Pendle YT",
        "Ethena",
        "USDe",
        "sUSDe",
        "Morpho",
        "Morpho Blue",
        "MetaMorpho",
        "Fluid",
        "Fluid Lending",
        "Euler",
        "Euler V2",
        "Silo Finance",
        "Silo V2",
        "Maple Finance",
        "Syrup",
        "Gearbox Protocol",
        "Credit Account",
        "Venus Protocol",
        "Radiant Capital",
        "Camelot DEX",
        "Aerodrome Finance",
        "Velodrome",
        "Hyperliquid",
        "Hyperliquid HLP",
        "GMX",
        "GMX V2",
        "Jupiter",
        "Jupiter Perps",
        "Drift Protocol",
        "Kamino Finance",
        "Kamino Lend",
        "Orca",
        "Whirlpool",
        "Raydium",
        "Marinade Finance",
        "mSOL",
        "Lido",
        "stETH",
        "Rocket Pool",
        "rETH",
        "EigenLayer",
        "EigenDA",
        "Symbiotic",
        "Mellow Protocol",
        "Renzo",
        "ezETH",
        "Ether.fi",
        "eETH",
        "Kelp DAO",
        "rsETH",
        "Frax Finance",
        "FRAX",
        "sFRAX",
        "Liquity",
        "LUSD",
        "Curve Lending",
        "Yearn Finance",
        "Beefy Finance",
        "Convex Finance",
        "Aura Finance",
        "Enzyme Finance",
        "Instadapp",
        "DeFi Saver",
        "CoW Swap",
        "1inch",
        "KyberSwap",
        "dYdX",
        "Synthetix",
        "Kwenta",
        "Lyra",
        "Ribbon Finance",
        "Opyn",
        "Ribbon Vault",
        "THORChain",
        "Maya Protocol",
        "Osmosis",
        "Injective",
        "Marginfi",
        "Solend",
        "Jito",
        "JitoSOL",
        "Sanctum",
        "Solana DeFi",
        "Base DeFi",
        "Arbitrum DeFi",
        "Optimism DeFi",
        "DeFi Governance",
        "Governance Proposal",
        "DAO Vote",
        "Delegate",
        "Timelock",
        "Protocol Treasury",
        "Treasury Diversification",
        "Protocol Revenue",
        "Protocol Fees",
        "Fee Switch",
        "Revenue Sharing",
        "Tokenomics",
        "Token Emissions",
        "Emission Schedule",
        "Token Unlock",
        "Total Value Locked",
        "TVL",
        "Capital Efficiency",
        "DeFi Security",
        "Smart Contract Audit",
        "DeFi Exploit",
        "Oracle Exploit",
        "Reentrancy Attack",
        "Access Control Vulnerability",
        "Economic Exploit",
        "Bug Bounty",
        "Risk Parameter",
        "Protocol Upgrade",
        "DeFi Integration",
        "Institutional DeFi",
        "DeFi Adoption",
        "DeFi Ecosystem"

    ],

    "boolean_queries": [

        "DeFi AND protocol launch",
        "DeFi AND mainnet launch",
        "DeFi AND testnet launch",
        "DeFi AND product launch",
        "DeFi AND protocol upgrade",
        "DeFi AND governance proposal",
        "DeFi AND DAO vote",
        "DeFi AND parameter update",
        "DeFi AND TVL growth",
        "DeFi AND TVL milestone",
        "DeFi AND liquidity mining",
        "DeFi AND incentive program",
        "DeFi AND liquidity incentive",
        "DeFi AND yield program",
        "DeFi AND airdrop",
        "DeFi AND exploit",
        "DeFi AND security incident",
        "DeFi AND smart contract audit",
        "DeFi AND vulnerability",
        "DeFi AND bug bounty",
        "DeFi AND partnership",
        "DeFi AND integration",
        "DeFi AND API integration",
        "DeFi AND cross-chain expansion",
        "DeFi AND bridge integration",
        "DeFi AND treasury allocation",
        "DeFi AND treasury diversification",
        "DeFi AND protocol revenue",
        "DeFi AND fee switch",
        "DeFi AND revenue sharing",
        "DeFi AND token launch",
        "DeFi AND tokenomics",
        "DeFi AND token unlock",
        "DeFi AND institutional adoption",
        "DeFi AND institutional liquidity",
        "DeFi AND ecosystem growth",
        "DeFi AND developer grant",
        "DeFi AND hackathon",
        "DeFi AND funding",
        "DeFi AND acquisition",
        "Aave AND governance",
        "Aave AND GHO",
        "Aave AND V4",
        "Compound AND proposal",
        "MakerDAO AND Sky",
        "Sky AND governance",
        "Spark AND lending",
        "Uniswap AND V4",
        "Uniswap AND hooks",
        "Uniswap AND fee switch",
        "Curve AND crvUSD",
        "Balancer AND upgrade",
        "Pendle AND integration",
        "Ethena AND USDe",
        "Morpho AND vault",
        "Fluid AND launch",
        "Euler AND upgrade",
        "Silo AND lending",
        "Maple AND institutional",
        "Gearbox AND leverage",
        "Venus AND BNB Chain",
        "Radiant AND cross-chain",
        "Camelot AND Arbitrum",
        "Aerodrome AND Base",
        "Hyperliquid AND perps",
        "GMX AND V2",
        "Jupiter AND Solana",
        "Drift AND Solana",
        "Kamino AND liquidity",
        "Orca AND Whirlpool",
        "Raydium AND launch",
        "Marinade AND staking",
        "Lido AND stETH",
        "Rocket Pool AND rETH",
        "EigenLayer AND AVS",
        "EigenLayer AND restaking",
        "Symbiotic AND restaking",
        "Chainlink AND DeFi integration",
        "Pyth AND oracle update",
        "RedStone AND oracle",
        "LayerZero AND DeFi",
        "Wormhole AND liquidity",
        "Axelar AND integration",
        "Across AND bridge",
        "stablecoin AND DeFi adoption",
        "CDP AND stablecoin",
        "RWA AND DeFi",
        "perpetual DEX AND launch",
        "options protocol AND upgrade",
        "yield aggregator AND strategy",
        "money market AND expansion",
        "liquid staking AND integration",
        "liquid restaking AND incentives",
        "MEV AND DeFi security",
        "flash loan AND exploit",
        "oracle AND manipulation",
        "DeFi bridge AND exploit",
        "DeFi vault AND audit",
        "DeFi protocol AND revenue",
        "DeFi protocol AND treasury",
        "DeFi DAO AND delegate",
        "DeFi AND risk parameter",
        "DeFi AND liquidity migration",
        "DeFi AND market maker",
        "DeFi AND user growth"

    ]

}
