FUNDING_QUERY_PACK = {

    "hashtags": [

        "#CryptoFunding",
        "#Web3Funding",
        "#BlockchainFunding",
        "#CryptoVC",
        "#Web3VC",
        "#VentureCapital",
        "#Fundraising",
        "#SeedRound",
        "#SeriesA",
        "#SeriesB",
        "#GrowthRound",
        "#StrategicInvestment",
        "#CryptoInvestment",
        "#Web3Investment",
        "#CryptoGrants",
        "#BuilderGrants",
        "#EcosystemFund",
        "#DeveloperFunding",
        "#CryptoAccelerator",
        "#Web3Accelerator",
        "#CryptoIncubator",
        "#TokenFundraising",
        "#InstitutionalCrypto",
        "#BlockchainVenture",
        "#StartupFunding",
        "#CryptoMergers",
        "#Web3Growth"

    ],

    "keywords": [

        "Fundraising",
        "Capital Raise",
        "Funding Round",
        "Investment Round",
        "Venture Investment",
        "Equity Financing",
        "Token Financing",
        "Private Sale",
        "Public Sale",
        "Token Sale",
        "Strategic Investment",
        "Lead Investor",
        "Co-Lead Investor",
        "Follow-On Investment",
        "Portfolio Company",
        "Venture Capital",
        "Crypto Venture Capital",
        "Web3 Venture Capital",
        "Pre-Seed",
        "Seed Round",
        "Series A",
        "Series B",
        "Series C",
        "Series D",
        "Growth Round",
        "Late-Stage Funding",
        "Bridge Round",
        "Extension Round",
        "Convertible Note",
        "SAFE Agreement",
        "Valuation Cap",
        "Post-Money Valuation",
        "Unicorn Valuation",
        "Strategic Round",
        "Corporate Venture Capital",
        "Venture Debt",
        "Revenue-Based Financing",
        "Liquidity Event",
        "Secondary Sale",
        "Secondary Transaction",
        "Acquisition",
        "Merger",
        "Mergers and Acquisitions",
        "Asset Purchase",
        "Acqui-Hire",
        "Strategic Partnership",
        "Joint Venture",
        "Ecosystem Fund",
        "Ecosystem Incentive Program",
        "Community Fund",
        "Developer Fund",
        "Builder Grant",
        "Developer Grant",
        "Research Grant",
        "Public Goods Funding",
        "Retroactive Public Goods Funding",
        "RetroPGF",
        "Quadratic Funding",
        "Grant Program",
        "Grant Round",
        "Grant Recipient",
        "Foundation Grant",
        "Protocol Grant",
        "Treasury",
        "Treasury Allocation",
        "Treasury Diversification",
        "Treasury Management",
        "DAO Treasury",
        "Governance Proposal",
        "On-Chain Vote",
        "Token Incentive",
        "Liquidity Incentive",
        "Developer Incentive",
        "Builder Incentive",
        "Ecosystem Expansion",
        "Ecosystem Growth",
        "Hackathon",
        "Bounty Program",
        "Developer Competition",
        "Incubator",
        "Startup Incubator",
        "Accelerator",
        "Startup Accelerator",
        "Venture Studio",
        "Launchpad",
        "Startup Program",
        "Founder Program",
        "Angel Investor",
        "Syndicate",
        "Limited Partner",
        "General Partner",
        "Fund Close",
        "Fund I",
        "Fund II",
        "Fund III",
        "Venture Fund",
        "Crypto Fund",
        "Web3 Fund",
        "Fund Deployment",
        "Investment Thesis",
        "Due Diligence",
        "Term Sheet",
        "Deal Flow",
        "a16z Crypto",
        "Andreessen Horowitz",
        "Paradigm",
        "Polychain Capital",
        "Pantera Capital",
        "Framework Ventures",
        "Electric Capital",
        "Multicoin Capital",
        "Dragonfly",
        "Dragonfly Capital",
        "Coinbase Ventures",
        "Binance Labs",
        "YZi Labs",
        "OKX Ventures",
        "Animoca Brands",
        "HashKey Capital",
        "Delphi Ventures",
        "Delphi Digital",
        "Blockchain Capital",
        "Spartan Group",
        "Mechanism Capital",
        "Galaxy Ventures",
        "Hack VC",
        "Robot Ventures",
        "Variant Fund",
        "CoinFund",
        "Maven 11",
        "Hypersphere Ventures",
        "Arrington Capital",
        "1kx",
        "Amber Group",
        "Arca",
        "Arrington XRP Capital",
        "Bain Capital Crypto",
        "Big Brain Holdings",
        "BlockTower Capital",
        "Brevan Howard Digital",
        "CMS Holdings",
        "CoinShares Ventures",
        "CMT Digital",
        "DCG",
        "DWF Ventures",
        "Fabric Ventures",
        "Fenbushi Capital",
        "Galaxy Digital",
        "GSR",
        "Hashed",
        "Jump Crypto",
        "Kenetic Capital",
        "KR1",
        "Lemniscap",
        "Lightspeed Faction",
        "MH Ventures",
        "Morningstar Ventures",
        "NFX",
        "North Island Ventures",
        "ParaFi Capital",
        "Placeholder VC",
        "Republic Crypto",
        "RockawayX",
        "Shima Capital",
        "Sfermion",
        "Sixth Man Ventures",
        "Solana Ventures",
        "The Spartan Group",
        "Three Arrows Capital",
        "Tribe Capital",
        "Two Sigma Ventures",
        "Wintermute Ventures",
        "BlackRock",
        "Fidelity",
        "Franklin Templeton",
        "Grayscale",
        "VanEck",
        "Bitwise",
        "Ark Invest",
        "Invesco",
        "WisdomTree",
        "State Street",
        "JPMorgan",
        "Goldman Sachs",
        "Morgan Stanley",
        "BNY Mellon",
        "Institutional Adoption",
        "Institutional Investment",
        "Digital Asset Fund",
        "Crypto ETF",
        "Spot Bitcoin ETF",
        "Tokenized Fund",
        "Tokenized Treasury",
        "Real World Assets",
        "RWA Fund",
        "Ethereum Foundation",
        "Solana Foundation",
        "Polygon Labs",
        "Arbitrum Foundation",
        "Optimism Foundation",
        "Base Ecosystem Fund",
        "Avalanche Foundation",
        "Aptos Foundation",
        "Sui Foundation",
        "NEAR Foundation",
        "Starknet Foundation",
        "zkSync Era",
        "Scroll Ecosystem",
        "Celestia Foundation",
        "Cosmos Hub",
        "Osmosis Grants",
        "Gitcoin Grants",
        "Octant",
        "Protocol Guild",
        "Uniswap Foundation",
        "Aave Grants DAO",
        "MakerDAO Endgame",
        "Nouns DAO",
        "Moloch DAO",
        "DAO Grant",
        "Crypto Philanthropy",
        "Impact Funding",
        "Open Source Funding",
        "Security Grant",
        "Audit Grant",
        "Research Fellowship",
        "Developer Relations Fund",
        "Liquidity Mining",
        "Points Program",
        "Ecosystem Airdrop",
        "Market Maker Investment",
        "Strategic Treasury Investment",
        "Corporate Treasury",
        "Bitcoin Treasury Company",
        "Crypto Startup",
        "Web3 Startup",
        "Blockchain Startup",
        "DeFi Fund",
        "Infrastructure Fund",
        "Gaming Fund",
        "AI Fund",
        "DePIN Fund",
        "NFT Fund",
        "Funding Announcement",
        "Investment Announcement",
        "Capital Commitment"

    ],

    "boolean_queries": [

        "crypto AND fundraising",
        "Web3 AND fundraising",
        "blockchain AND funding round",
        "crypto AND capital raise",
        "Web3 AND investment round",
        "crypto startup AND seed round",
        "crypto startup AND Series A",
        "crypto startup AND Series B",
        "crypto startup AND growth round",
        "blockchain AND strategic investment",
        "crypto AND lead investor",
        "Web3 AND venture investment",
        "crypto AND private sale",
        "token AND financing round",
        "crypto AND valuation",
        "crypto AND acquisition",
        "Web3 AND acquisition",
        "crypto AND merger",
        "blockchain AND acqui-hire",
        "crypto AND strategic partnership",
        "crypto AND ecosystem fund",
        "Web3 AND ecosystem fund",
        "blockchain AND developer fund",
        "crypto AND builder grant",
        "Web3 AND developer grant",
        "crypto AND grant program",
        "crypto AND grant recipient",
        "protocol AND research grant",
        "DAO AND public goods funding",
        "Gitcoin AND grants round",
        "crypto AND treasury allocation",
        "DAO AND treasury proposal",
        "DAO AND treasury diversification",
        "protocol AND treasury management",
        "crypto AND ecosystem incentive",
        "Web3 AND developer incentive",
        "blockchain AND builder incentive",
        "crypto AND hackathon",
        "Web3 AND bounty program",
        "blockchain AND developer competition",
        "crypto AND incubator",
        "Web3 AND accelerator",
        "blockchain AND venture studio",
        "crypto AND launchpad",
        "a16z Crypto AND investment",
        "Paradigm AND investment",
        "Polychain AND investment",
        "Pantera AND investment",
        "Framework Ventures AND investment",
        "Electric Capital AND investment",
        "Multicoin Capital AND investment",
        "Dragonfly AND investment",
        "Coinbase Ventures AND investment",
        "Binance Labs AND investment",
        "OKX Ventures AND investment",
        "Animoca Brands AND investment",
        "HashKey Capital AND investment",
        "Delphi Ventures AND investment",
        "Blockchain Capital AND investment",
        "Spartan Group AND investment",
        "Mechanism Capital AND investment",
        "Galaxy Ventures AND investment",
        "Hack VC AND investment",
        "Robot Ventures AND investment",
        "Variant Fund AND investment",
        "CoinFund AND investment",
        "Maven 11 AND investment",
        "Hypersphere AND investment",
        "Arrington Capital AND investment",
        "BlackRock AND crypto investment",
        "Fidelity AND digital assets",
        "Franklin Templeton AND tokenized fund",
        "Grayscale AND fund launch",
        "VanEck AND crypto ETF",
        "Bitwise AND institutional adoption",
        "institutional AND crypto allocation",
        "institutional AND blockchain adoption",
        "Ethereum Foundation AND grant",
        "Solana Foundation AND grant",
        "Arbitrum Foundation AND grant",
        "Optimism Foundation AND grant",
        "Avalanche Foundation AND incentive",
        "Aptos Foundation AND ecosystem",
        "Sui Foundation AND developer",
        "NEAR Foundation AND funding",
        "Starknet Foundation AND grant",
        "zkSync AND ecosystem fund",
        "Uniswap Foundation AND grant",
        "Aave Grants DAO AND proposal",
        "crypto AND fund close",
        "crypto AND new venture fund",
        "Web3 AND fund deployment",
        "crypto AND portfolio investment",
        "DeFi AND funding announcement",
        "AI AND crypto funding",
        "DePIN AND funding",
        "gaming AND Web3 funding",
        "infrastructure AND crypto funding",
        "crypto AND capital commitment"

    ]

}
