NFT_QUERY_PACK = {

    "hashtags": [

        "#NFT",
        "#NFTs",
        "#DigitalCollectibles",
        "#NFTCommunity",
        "#NFTArt",
        "#NFTGaming",
        "#GamingNFT",
        "#NFTMarketplace",
        "#NFTMint",
        "#NFTDrop",
        "#NFTLaunch",
        "#NFTAnalytics",
        "#NFTSecurity",
        "#NFTFi",
        "#Ordinals",
        "#BitcoinNFTs",
        "#Runes",
        "#EthereumNFTs",
        "#SolanaNFTs",
        "#BaseNFT",
        "#OnchainArt",
        "#DigitalIdentity",
        "#SoulboundToken",
        "#Metaverse",
        "#CreatorEconomy",
        "#Web3Gaming",
        "#CrossChainNFT"

    ],

    "keywords": [

        "Non-Fungible Token",
        "NFT",
        "Digital Collectible",
        "Digital Asset",
        "Tokenized Collectible",
        "NFT Collection",
        "NFT Drop",
        "NFT Launch",
        "NFT Mint",
        "Mint Date",
        "Allowlist",
        "Whitelist",
        "Public Mint",
        "Free Mint",
        "Fair Mint",
        "Dutch Auction",
        "Mint Pass",
        "Minting Contract",
        "Generative Art",
        "On-Chain Art",
        "Digital Art",
        "Profile Picture NFT",
        "PFP",
        "Avatar Collection",
        "NFT Marketplace",
        "NFT Aggregator",
        "NFT Aggregation",
        "NFT Launchpad",
        "NFT Auction",
        "Secondary Sale",
        "Floor Price",
        "Floor Sweep",
        "NFT Volume",
        "NFT Liquidity",
        "NFT Index",
        "NFT Fund",
        "NFT Portfolio",
        "NFT Analytics",
        "NFT Data",
        "NFT API",
        "NFT Metadata",
        "Metadata API",
        "Metadata Standard",
        "Metadata Refresh",
        "Trait Rarity",
        "Rarity Score",
        "Collection Ranking",
        "NFT Valuation",
        "NFT Appraisal",
        "NFT Royalty",
        "Creator Royalty",
        "Royalty Enforcement",
        "Royalty Registry",
        "Creator Fee",
        "IP Licensing",
        "Intellectual Property",
        "Commercial Rights",
        "Brand Licensing",
        "Creator Economy",
        "NFT Lending",
        "NFT Borrowing",
        "NFT Collateral",
        "NFT Loan",
        "NFT Financing",
        "NFT Fractionalization",
        "Fractional NFT",
        "NFT Vault",
        "NFT Perpetual",
        "NFT AMM",
        "NFTFi",
        "NFT Staking",
        "NFT Yield",
        "NFT Insurance",
        "ERC-721",
        "ERC-1155",
        "ERC-6551",
        "Token Bound Account",
        "ERC-4907",
        "Rental NFT",
        "ERC-2981",
        "NFT Royalty Standard",
        "Soulbound Token",
        "SBT",
        "Digital Identity",
        "Verifiable Credential",
        "Decentralized Identity",
        "Dynamic NFT",
        "Evolving NFT",
        "Programmable NFT",
        "Composable NFT",
        "Cross-Chain NFT",
        "NFT Bridge",
        "Interoperable NFT",
        "Multi-Chain NFT",
        "NFT Wallet",
        "NFT Custody",
        "NFT Infrastructure",
        "NFT Indexer",
        "NFT Data Provider",
        "NFT Oracle",
        "NFT Storage",
        "IPFS",
        "Arweave",
        "Decentralized Storage",
        "Ordinals",
        "Bitcoin Ordinals",
        "Ordinal Inscription",
        "Bitcoin NFT",
        "Bitcoin Inscriptions",
        "Runes",
        "Runestone",
        "BRC-20",
        "Rare Sats",
        "Sats Name Service",
        "OpenSea",
        "Blur",
        "Magic Eden",
        "Tensor",
        "Foundation",
        "SuperRare",
        "Rarible",
        "Zora",
        "Manifold",
        "Reservoir",
        "LooksRare",
        "X2Y2",
        "Nifty Gateway",
        "Sotheby's Metaverse",
        "Christie's 3.0",
        "OpenSea Pro",
        "Blur Blend",
        "Magic Eden Wallet",
        "Tensor Swap",
        "Zora Network",
        "Manifold Studio",
        "Reservoir Protocol",
        "Immutable",
        "Immutable X",
        "Immutable zkEVM",
        "Treasure",
        "TreasureDAO",
        "Ronin",
        "Polygon Gaming",
        "ApeChain",
        "Flow",
        "Dapper Labs",
        "The Sandbox",
        "Decentraland",
        "Otherside",
        "Somnia",
        "Pudgy Penguins",
        "Bored Ape Yacht Club",
        "BAYC",
        "CryptoPunks",
        "Azuki",
        "Doodles",
        "Milady",
        "Moonbirds",
        "Mutant Ape Yacht Club",
        "MAYC",
        "Bored Ape Kennel Club",
        "Meebits",
        "Clone X",
        "DeGods",
        "y00ts",
        "Mad Lads",
        "Captainz",
        "CryptoDickbutts",
        "Art Blocks",
        "Chromie Squiggle",
        "World of Women",
        "Cool Cats",
        "Nouns",
        "OnChainMonkey",
        "NodeMonkes",
        "Bitcoin Puppets",
        "Quantum Cats",
        "NBA Top Shot",
        "Sorare",
        "Axie Infinity",
        "Gods Unchained",
        "Parallel",
        "Pixels",
        "Illuvium",
        "Guild of Guardians",
        "Play-to-Earn",
        "NFT Game Asset",
        "Virtual Land",
        "Metaverse Land",
        "Wearable NFT",
        "Music NFT",
        "Fashion NFT",
        "Photography NFT",
        "Sports Collectible",
        "Ticketing NFT",
        "Membership NFT",
        "Proof of Attendance Protocol",
        "POAP",
        "NFT Security",
        "NFT Scam",
        "Phishing",
        "Wallet Drainer",
        "Malicious Mint",
        "Fake Collection",
        "Counterfeit NFT",
        "Metadata Rug Pull",
        "NFT Exploit",
        "Wash Trading",
        "Sybil Farming",
        "Insider Trading",
        "NFT Whale",
        "Institutional NFT",
        "Yuga Labs",
        "PROOF Collective",
        "Chiru Labs",
        "Azuki DAO",
        "Pudgy Toys",
        "Pixel Vault",
        "Animoca Brands",
        "Panini Blockchain",
        "Rarible Protocol",
        "Alchemy NFT API",
        "Moralis NFT API",
        "SimpleHash",
        "Dune Analytics",
        "Nansen NFT",
        "NFTGo",
        "OpenSea API",
        "Etherscan NFT"

    ],

    "boolean_queries": [

        "NFT AND launch",
        "NFT AND collection announcement",
        "NFT AND mint date",
        "NFT AND public mint",
        "NFT AND allowlist",
        "NFT AND whitelist",
        "NFT AND mint pass",
        "NFT AND reveal",
        "NFT AND roadmap",
        "NFT AND partnership",
        "NFT AND collaboration",
        "NFT AND brand partnership",
        "NFT AND marketplace integration",
        "NFT AND marketplace listing",
        "NFT AND aggregator integration",
        "NFT AND royalty",
        "NFT AND royalty enforcement",
        "NFT AND creator fee",
        "NFT AND acquisition",
        "NFT AND funding",
        "NFT AND investment round",
        "NFT AND seed round",
        "NFT AND grant",
        "NFT AND security incident",
        "NFT AND exploit",
        "NFT AND vulnerability",
        "NFT AND phishing",
        "NFT AND wallet drainer",
        "NFT AND scam",
        "NFT AND wash trading",
        "NFT AND suspicious volume",
        "NFT AND whale purchase",
        "NFT AND whale activity",
        "NFT AND floor sweep",
        "NFT AND institutional adoption",
        "NFT AND enterprise adoption",
        "NFT AND creator launch",
        "NFT AND artist collaboration",
        "NFT AND developer update",
        "NFT AND GitHub release",
        "NFT AND API update",
        "NFT AND infrastructure",
        "NFT AND ecosystem growth",
        "NFT AND cross-chain",
        "NFT AND bridge",
        "NFT AND lending",
        "NFT AND fractionalization",
        "NFT AND index",
        "NFT AND fund",
        "NFT AND governance",
        "NFT AND DAO proposal",
        "NFT AND token launch",
        "NFT AND airdrop",
        "NFT AND gaming",
        "NFT AND metaverse",
        "NFT AND digital identity",
        "NFT AND soulbound",
        "Ordinals AND launch",
        "Ordinals AND collection",
        "Ordinals AND marketplace",
        "Ordinals AND mint",
        "Runes AND launch",
        "Runes AND protocol update",
        "Bitcoin NFT AND partnership",
        "OpenSea AND launch",
        "OpenSea AND integration",
        "OpenSea AND royalty",
        "Blur AND launch",
        "Blur AND Blend",
        "Magic Eden AND integration",
        "Magic Eden AND Bitcoin",
        "Tensor AND Solana",
        "Foundation AND artist",
        "SuperRare AND exhibition",
        "Rarible AND protocol",
        "Zora AND creator",
        "Manifold AND contract",
        "Reservoir AND API",
        "LooksRare AND rewards",
        "Immutable AND gaming",
        "Treasure AND ecosystem",
        "Pudgy Penguins AND partnership",
        "Bored Ape Yacht Club AND announcement",
        "CryptoPunks AND sale",
        "Azuki AND launch",
        "Doodles AND partnership",
        "Milady AND ecosystem",
        "Moonbirds AND PROOF",
        "ERC-721 AND standard",
        "ERC-1155 AND integration",
        "ERC-6551 AND token bound account",
        "ERC-4907 AND rental",
        "NFT marketplace AND acquisition",
        "NFT analytics AND data",
        "NFT wallet AND security",
        "NFT launchpad AND funding",
        "NFT creator AND licensing",
        "NFT protocol AND upgrade"

    ]

}
