APTOS_QUERY_PACK = {

    "hashtags": [
        "#Aptos",
        "#APT",
        "#AptosEcosystem",
        "#Move",
        "#MoveLanguage",
        "#Web3",
        "#Layer1",
        "#Blockchain",
        "#Crypto",
        "#DeFi",
        "#NFT",
        "#Gaming",
        "#AptosFoundation",
        "#AptosLabs",
        "#ParallelExecution"
    ],

    "keywords": [
        "Aptos",
        "APT",
        "Aptos Labs",
        "Aptos Foundation",
        "Move",
        "Move Language",
        "Move VM",
        "Block STM",
        "Parallel Execution",
        "Aptos Governance",
        "Aptos Staking",
        "Aptos Validators",
        "Aptos Grants",
        "Aptos Ecosystem Fund",
        "Aptos Wallet",
        "Petra Wallet",
        "Martian Wallet",
        "Pontem",
        "Thala Labs",
        "Amnis Finance",
        "Merkle Trade",
        "Aries Markets",
        "Econia",
        "LayerZero",
        "Cross Chain",
        "Developer Tools",
        "Aptos SDK",
        "Mainnet Upgrade",
        "Protocol Upgrade",
        "Partnership Announcement",
        "Hackathon",
        "Ecosystem Growth",
        "Stablecoin",
        "Tokenization",
        "Real World Assets",
        "Institutional Adoption",
        "Consumer Applications",
        "High Throughput",
        "Low Latency",
        "Aptos Network"
    ],

    "boolean_queries": [
        "Aptos AND funding",
        "Aptos AND partnership",
        "Aptos AND grant",
        "Aptos AND governance",
        "Aptos AND validator",
        "Aptos AND staking",
        "Aptos AND ecosystem",
        "Aptos AND launch",
        "Aptos AND mainnet",
        "Aptos AND developer",
        "Aptos AND protocol",
        "Aptos AND Move",
        "Aptos AND Block STM",
        "Aptos AND DeFi",
        "Aptos AND NFT",
        "Aptos AND gaming",
        "Aptos AND adoption",
        "Aptos AND RWA",
        "Aptos AND ecosystem growth",
        "Aptos AND upgrade"
    ]

}