BERACHAIN_QUERY_PACK = {

    "hashtags": [
        "#Berachain",
        "#BERA",
        "#ProofOfLiquidity",
        "#PoL",
        "#Boyco",
        "#Honey",
        "#BGT",
        "#Bera",
        "#DeFi",
        "#Web3",
        "#Layer1",
        "#Blockchain",
        "#Crypto",
        "#BerachainFoundation",
        "#Ecosystem"
    ],

    "keywords": [
        "Berachain",
        "BERA",
        "Proof of Liquidity",
        "PoL",
        "BGT",
        "Honey",
        "Boyco",
        "BeaconKit",
        "Berachain Foundation",
        "Berachain Validators",
        "Berachain Governance",
        "Berachain Mainnet",
        "Berachain Testnet",
        "Berachain Ecosystem",
        "Infrared Finance",
        "Kodiak",
        "BEX",
        "Dolomite",
        "Concrete",
        "Berps",
        "Bulla Exchange",
        "Developer Grants",
        "Liquidity Incentives",
        "Yield Farming",
        "Restaking",
        "Liquid Staking",
        "Protocol Upgrade",
        "Governance Proposal",
        "Partnership Announcement",
        "Cross Chain",
        "Stablecoin",
        "Institutional Adoption",
        "Developer Tools",
        "Hackathon",
        "Ecosystem Growth",
        "On Chain Liquidity",
        "DEX",
        "Lending",
        "High Performance",
        "Berachain Network"
    ],

    "boolean_queries": [
        "Berachain AND funding",
        "Berachain AND partnership",
        "Berachain AND governance",
        "Berachain AND validator",
        "Berachain AND ecosystem",
        "Berachain AND Proof of Liquidity",
        "Berachain AND PoL",
        "Berachain AND BGT",
        "Berachain AND Honey",
        "Berachain AND Boyco",
        "Berachain AND mainnet",
        "Berachain AND developer",
        "Berachain AND grants",
        "Berachain AND DeFi",
        "Berachain AND liquidity",
        "Berachain AND staking",
        "Berachain AND protocol",
        "Berachain AND adoption",
        "Berachain AND upgrade",
        "Berachain AND ecosystem growth"
    ]

}