CELESTIA_QUERY_PACK = {

    "hashtags": [
        "#Celestia",
        "#TIA",
        "#ModularBlockchain",
        "#Modular",
        "#DataAvailability",
        "#Rollups",
        "#Blockchain",
        "#Crypto",
        "#Web3",
        "#Layer2",
        "#Infrastructure",
        "#CelestiaEcosystem",
        "#Scaling",
        "#Developer",
        "#TIAEcosystem"
    ],

    "keywords": [
        "Celestia",
        "TIA",
        "Celestia Foundation",
        "Celestia Labs",
        "Modular Blockchain",
        "Data Availability",
        "Blobstream",
        "Data Availability Sampling",
        "DAS",
        "Rollups",
        "Optimistic Rollups",
        "ZK Rollups",
        "Light Nodes",
        "Consensus",
        "Validator",
        "Staking",
        "Governance",
        "Mainnet",
        "Protocol Upgrade",
        "Developer SDK",
        "Modular Infrastructure",
        "Builder Program",
        "Grant Program",
        "Hackathon",
        "Cross Chain",
        "Layer 2",
        "Ethereum Rollups",
        "Scaling",
        "Interoperability",
        "High Throughput",
        "Infrastructure",
        "Partnership",
        "Research",
        "Node Operator",
        "Data Layer",
        "Execution Layer",
        "Availability Layer",
        "Protocol Launch",
        "Ecosystem Growth",
        "Celestia Ecosystem"
    ],

    "boolean_queries": [
        "Celestia AND funding",
        "Celestia AND partnership",
        "Celestia AND governance",
        "Celestia AND validator",
        "Celestia AND staking",
        "Celestia AND rollups",
        "Celestia AND modular blockchain",
        "Celestia AND data availability",
        "Celestia AND Blobstream",
        "Celestia AND DAS",
        "Celestia AND developer",
        "Celestia AND protocol",
        "Celestia AND mainnet",
        "Celestia AND Layer2",
        "Celestia AND scaling",
        "Celestia AND interoperability",
        "Celestia AND adoption",
        "Celestia AND infrastructure",
        "Celestia AND ecosystem",
        "Celestia AND ecosystem growth"
    ]

}