COSMOS_QUERY_PACK = {

    "hashtags": [
        "#Cosmos",
        "#ATOM",
        "#CosmosHub",
        "#IBC",
        "#Interchain",
        "#CosmosEcosystem",
        "#CosmosSDK",
        "#CometBFT",
        "#Web3",
        "#DeFi",
        "#Layer1",
        "#Blockchain",
        "#Crypto",
        "#AppChain",
        "#Interoperability"
    ],

    "keywords": [
        "Cosmos",
        "ATOM",
        "Cosmos Hub",
        "Interchain",
        "IBC",
        "Inter Blockchain Communication",
        "Cosmos SDK",
        "CometBFT",
        "Tendermint",
        "Interchain Security",
        "Replicated Security",
        "Consumer Chain",
        "Provider Chain",
        "Cosmos Governance",
        "Cosmos Staking",
        "Cosmos Validator",
        "Cosmos Foundation",
        "Interchain Foundation",
        "Cosmos Grants",
        "AppChain",
        "Application Specific Blockchain",
        "Interchain Stack",
        "Cross Chain",
        "Cross Chain Liquidity",
        "Cross Chain Messaging",
        "Osmosis",
        "dYdX Chain",
        "Neutron",
        "Celestia",
        "Noble",
        "Stride",
        "Saga",
        "Akash",
        "Developer Tools",
        "Mainnet Upgrade",
        "Protocol Upgrade",
        "Ecosystem Fund",
        "Partnership Announcement",
        "Blockchain Interoperability",
        "Cosmos Ecosystem"
    ],

    "boolean_queries": [
        "Cosmos AND funding",
        "Cosmos AND partnership",
        "Cosmos AND grant",
        "Cosmos AND governance",
        "Cosmos AND validator",
        "Cosmos AND staking",
        "Cosmos AND ecosystem",
        "Cosmos AND launch",
        "Cosmos AND mainnet",
        "Cosmos AND developer",
        "Cosmos AND protocol",
        "Cosmos AND IBC",
        "Cosmos AND Interchain",
        "Cosmos AND SDK",
        "Cosmos AND interoperability",
        "Cosmos AND AppChain",
        "Cosmos AND security",
        "Cosmos AND adoption",
        "Cosmos AND upgrade",
        "Cosmos AND ecosystem growth"
    ]

}