HYPERLIQUID_QUERY_PACK = {

    "hashtags": [
        "#Hyperliquid",
        "#HYPE",
        "#HyperEVM",
        "#Perps",
        "#DEX",
        "#DeFi",
        "#Crypto",
        "#Blockchain",
        "#Web3",
        "#Trading",
        "#OnChain",
        "#HyperliquidEcosystem",
        "#Perpetuals",
        "#OrderBook",
        "#Layer1"
    ],

    "keywords": [
        "Hyperliquid",
        "HYPE",
        "HyperEVM",
        "HyperBFT",
        "Hyperliquid Foundation",
        "Hyperliquid Ecosystem",
        "Hyperliquid Validator",
        "Hyperliquid Governance",
        "Hyperliquid Mainnet",
        "Perpetual Futures",
        "Perpetual Trading",
        "On Chain Order Book",
        "Spot Trading",
        "Cross Margin",
        "Isolated Margin",
        "Liquidity Provider",
        "Market Maker",
        "Trading Competition",
        "Vault Strategy",
        "Vault",
        "HyperEVM Launch",
        "Bridge",
        "Developer SDK",
        "Protocol Upgrade",
        "Governance Proposal",
        "Trading Volume",
        "Open Interest",
        "Liquidation",
        "Leverage",
        "DeFi",
        "Stablecoin",
        "Institutional Trading",
        "MEV",
        "Low Latency",
        "High Throughput",
        "Partnership Announcement",
        "Ecosystem Growth",
        "Builder Program",
        "Hyperliquid Network",
        "On Chain Finance"
    ],

    "boolean_queries": [
        "Hyperliquid AND funding",
        "Hyperliquid AND partnership",
        "Hyperliquid AND governance",
        "Hyperliquid AND HyperEVM",
        "Hyperliquid AND HyperBFT",
        "Hyperliquid AND validator",
        "Hyperliquid AND ecosystem",
        "Hyperliquid AND trading volume",
        "Hyperliquid AND open interest",
        "Hyperliquid AND perpetuals",
        "Hyperliquid AND protocol",
        "Hyperliquid AND bridge",
        "Hyperliquid AND DeFi",
        "Hyperliquid AND developer",
        "Hyperliquid AND upgrade",
        "Hyperliquid AND institutional",
        "Hyperliquid AND launch",
        "Hyperliquid AND adoption",
        "Hyperliquid AND ecosystem growth",
        "Hyperliquid AND mainnet"
    ]

}