NEAR_QUERY_PACK = {

    "hashtags": [
        "#NEAR",
        "#NEARProtocol",
        "#NearAI",
        "#ChainAbstraction",
        "#BOS",
        "#BlockchainOS",
        "#Web3",
        "#DeFi",
        "#NFT",
        "#Gaming",
        "#Layer1",
        "#Crypto",
        "#NearEcosystem",
        "#JavaScript",
        "#AI"
    ],

    "keywords": [
        "NEAR Protocol",
        "NEAR",
        "Near Foundation",
        "Near One",
        "Chain Abstraction",
        "Blockchain Operating System",
        "BOS",
        "Near AI",
        "AI Hub",
        "Intents",
        "FastAuth",
        "Near Wallet",
        "Near Governance",
        "Near Validators",
        "Near Staking",
        "Near Grants",
        "Near Horizon",
        "Near Ecosystem",
        "Near Data Availability",
        "Near DA",
        "Shade Agents",
        "Omni Bridge",
        "Rainbow Bridge",
        "Aurora",
        "Aurora EVM",
        "Sweat Economy",
        "Ref Finance",
        "Orderly Network",
        "Near JavaScript SDK",
        "Developer Tools",
        "Protocol Upgrade",
        "Mainnet Upgrade",
        "Partnership Announcement",
        "Hackathon",
        "AI x Blockchain",
        "Web3 AI",
        "Cross Chain",
        "Consumer Crypto",
        "Near Ecosystem Fund",
        "Near Protocol Ecosystem"
    ],

    "boolean_queries": [
        "NEAR AND funding",
        "NEAR AND partnership",
        "NEAR AND grant",
        "NEAR AND governance",
        "NEAR AND validator",
        "NEAR AND staking",
        "NEAR AND ecosystem",
        "NEAR AND launch",
        "NEAR AND mainnet",
        "NEAR AND developer",
        "NEAR AND protocol",
        "NEAR AND AI",
        "NEAR AND Chain Abstraction",
        "NEAR AND BOS",
        "NEAR AND Aurora",
        "NEAR AND Intents",
        "NEAR AND hackathon",
        "NEAR AND adoption",
        "NEAR AND ecosystem growth",
        "NEAR AND upgrade"
    ]

}