POLYGON_QUERY_PACK = {

    "hashtags": [
        "#Polygon",
        "#MATIC",
        "#PolygonEcosystem",
        "#PolygonLabs",
        "#PolygonCDK",
        "#PolygonPoS",
        "#PolygonzkEVM",
        "#AggLayer",
        "#Web3",
        "#DeFi",
        "#NFT",
        "#Gaming",
        "#Ethereum",
        "#Layer2",
        "#Crypto"
    ],

    "keywords": [
        "Polygon",
        "MATIC",
        "POL",
        "Polygon Labs",
        "Polygon Foundation",
        "Polygon PoS",
        "Polygon zkEVM",
        "AggLayer",
        "Polygon CDK",
        "Chain Development Kit",
        "Ethereum Layer 2",
        "ZK Rollup",
        "Validium",
        "Zero Knowledge",
        "Polygon Bridge",
        "Polygon Wallet",
        "Polygon ID",
        "Polygon Village",
        "Polygon Grants",
        "Polygon Governance",
        "Polygon Staking",
        "Polygon Validators",
        "Polygon Ecosystem",
        "Polygon SDK",
        "Polygon Supernets",
        "Astar zkEVM",
        "Immutable zkEVM",
        "Web3 Gaming",
        "NFT Infrastructure",
        "DeFi on Polygon",
        "Real World Assets",
        "Tokenization",
        "Enterprise Blockchain",
        "Developer Tools",
        "Mainnet Upgrade",
        "Ecosystem Fund",
        "Partnership Announcement",
        "Protocol Upgrade",
        "Scaling Ethereum",
        "Polygon Network"
    ],

    "boolean_queries": [
        "Polygon AND funding",
        "Polygon AND partnership",
        "Polygon AND grant",
        "Polygon AND governance",
        "Polygon AND validator",
        "Polygon AND staking",
        "Polygon AND ecosystem",
        "Polygon AND launch",
        "Polygon AND mainnet",
        "Polygon AND developer",
        "Polygon AND protocol",
        "Polygon AND zkEVM",
        "Polygon AND AggLayer",
        "Polygon AND CDK",
        "Polygon AND DeFi",
        "Polygon AND NFT",
        "Polygon AND gaming",
        "Polygon AND tokenization",
        "Polygon AND RWA",
        "Polygon AND adoption"
    ]

}