SEI_QUERY_PACK = {

    "hashtags": [
        "#Sei",
        "#SEI",
        "#SeiNetwork",
        "#ParallelExecution",
        "#DeFi",
        "#Gaming",
        "#Layer1",
        "#Crypto",
        "#Blockchain",
        "#Web3",
        "#SeiEcosystem",
        "#Trading",
        "#OrderMatching",
        "#SeiDevelopment",
        "#Performance"
    ],

    "keywords": [
        "Sei",
        "SEI",
        "Sei Network",
        "Sei Foundation",
        "Sei Labs",
        "Twin Turbo Consensus",
        "Parallel Execution",
        "Optimistic Block Processing",
        "Native Order Matching",
        "EVM Compatibility",
        "CosmWasm",
        "IBC",
        "Validator",
        "Staking",
        "Governance",
        "Mainnet",
        "Protocol Upgrade",
        "Developer SDK",
        "Hackathon",
        "Grant Program",
        "Ecosystem Fund",
        "Cross Chain",
        "High Throughput",
        "Low Latency",
        "DeFi",
        "DEX",
        "NFT",
        "Gaming",
        "Institutional Adoption",
        "Trading Infrastructure",
        "Liquidity",
        "Market Maker",
        "Builder Program",
        "Partnership",
        "Protocol Launch",
        "Infrastructure",
        "On Chain Trading",
        "Performance",
        "Developer Tools",
        "Sei Ecosystem"
    ],

    "boolean_queries": [
        "Sei AND funding",
        "Sei AND partnership",
        "Sei AND governance",
        "Sei AND validator",
        "Sei AND staking",
        "Sei AND ecosystem",
        "Sei AND developer",
        "Sei AND mainnet",
        "Sei AND upgrade",
        "Sei AND Parallel Execution",
        "Sei AND Twin Turbo",
        "Sei AND DeFi",
        "Sei AND gaming",
        "Sei AND liquidity",
        "Sei AND protocol",
        "Sei AND adoption",
        "Sei AND infrastructure",
        "Sei AND builder",
        "Sei AND grant",
        "Sei AND ecosystem growth"
    ]

}