"""Canonical relationship categories."""
from enum import StrEnum

class RelationshipType(StrEnum):
    FOUNDED = "founded"
    OWNS = "owns"
    MAINTAINS = "maintains"
    DEPLOYS = "deploys"
    INVESTED_IN = "invested_in"
    IMPLEMENTS = "implements"
    USES = "uses"
    ASSOCIATED_WITH = "associated_with"
    HAS_REPOSITORY = "has_repository"
    HAS_WEBSITE = "has_website"
    HAS_WALLET = "has_wallet"
    HAS_DISCORD = "has_discord"
    HAS_TELEGRAM = "has_telegram"
    CREATED = "created"
    MEMBER_OF = "member_of"
    WORKS_FOR = "works_for"
    CONTRIBUTES_TO = "contributes_to"
    DEPENDS_ON = "depends_on"
    FORKED_FROM = "forked_from"
    FUNDED_BY = "funded_by"
    MENTIONS = "mentions"
    FOLLOWS = "follows"
    COLLABORATES_WITH = "collaborates_with"
