from typing import Protocol
from .correlation_strategy import CorrelationStrategy
class CorrelationRegistry(Protocol):
    def register(self, name: str, strategy: CorrelationStrategy) -> None: ...
    def get(self, name: str) -> CorrelationStrategy | None: ...
